import Head from "next/head";
import { Map } from "@/components/Map/Map";

export default function Home() {
  return (
    <>
      <Head>
        <title>Yandex Map</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
    <Map />
      </main>
    </>
  );
}
